flatsurf/e-antic

e-antic/renfxx.h
cppcheck complained about these. It does not really make a difference in
practice but it's confusing that these are not passed by reference.
=> Pass strings by const ref

e-antic/renfxx.h
I guess it's safe to assume C++11 these days, see https://en.cppreference.com/w/cpp/language/nullptr.
=> Replace NULL with C++11 nullptr

e-antic/renfxx.h
so no implicit conversion happens from a field to the zero element in
that field. And similarly, no explicit conversion should be inteded from
a string as that is more likely a mistake.
=> Mark unexpected conversions as explicit

e-antic/renfxx.h, renfxx/renf_class.cpp, renfxx/renf_elem_class.cpp
I had forgotten about a few in the first run. The only non-trivial
new implementation is the operator bool. Everything else just moved from
the now deprecated implementation to the non-deprecated one.
=> Implement all methods declared in the C++ headers

e-antic/renfxx.h, renfxx/renf_class.cpp
char* are implicitly converted to std::string so there should be no
reason to keep this one around. (And now it prints deprecation warnings
if you do something like renf_class("…", "…", "…");)
=> Remove renf_class constructor

e-antic/nf.h, e-antic/nf_elem.h
Description: upstream: headers: reformat
Remove end-of-lines and space-at-begin-of-lines in view to parse
the headers to extract easily a version maps.
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2019-05-17
=> render installed headers systemwide

e-antic/renfxx.h, renfxx/renf_elem_class.cpp
clang does not understand the pragma and issues a warning
=> Ignore -Wterminate for GCC only

e-antic/renfxx.h
without this, there is no compile error (apparently is_integral is
forward declared somewhere) but one can create an unfortunate list of
includes and then get errors such as: `is_integral<int> has no member
value`, i.e., is_integral claims that int is not an integer.
=> Add type_traits for is_integral_v

renf/init_nth_root.c, renf/test/t-init_nth_root_fmpq.c
Should fix the remaining issue in #61
=> d should be positive in renf_init_nth_root_fmpq

ChangeLog, NEWS, e-antic/renfxx.h, renfxx/renf_class.cpp, renfxx/renf_elem_class.cpp, renfxx/test/t-assignment.cpp, renfxx/test/t-binop.cpp, renfxx/test/t-ceil.cpp, renfxx/test/t-cmp.cpp, renfxx/test/t-constructor.cpp, renfxx/test/t-get.cpp, renfxx/test/t-get_num_den.cpp, renfxx/test/t-get_str.cpp, renfxx/test/t-is_integer_rational.cpp, renfxx/test/t-pow.cpp, renfxx/test/t-stream.cpp
so cppyy can destroy objects in the right order, e.g., when closing a
Sage session.
=> Pass renf_class by shared_ptr

e-antic/renf.h, e-antic/renf_elem.h, e-antic/renfxx.h, e-antic/renfxx_cereal.h, e-antic/renfxx_fwd.h
at least the ones that actually guard e-antic headers
fixes #31.
=> Make type guards collision safe

e-antic/renfxx_cereal.h
and instead hook into cereal's shared_ptr serialization logic
(undocumented but part of the public API except for the "detail" which
is just 1 << 31.
=> Remove renf_class_cereal hack

e-antic/renfxx.h
in theory we can detect GNU GCC by checking for the GNUG definition.
However, lots of compilers set this unfortunately.
=> Squash compiler warnings

e-antic/renfxx.h, renfxx/renf_elem_class.cpp
this should speed up the operator= in some typical use cases.
Note that we do not need to dereference nf since we assume uniqueness
of renf_class, i.e., if the address is the same, we assume that the
content is the same.
=> Minor performance tweak for the C++ interface

renf_elem/cmp.c, renf_elem/cmp_fmpq.c, renf_elem/test/t-cmp.c
the comparison code uses NF_ELEM_NUMREF but this returns a NULL when
there are no coefficients.
=> Fix comparison of number field zero without coefficients

configure.ac, renf/test/t-thread.c
not a very pretty check but I did not find a better way determine that we are in a `make check-valgrind`.
=> Skip threading checks with memcheck

.travis.sh, .travis.yml
apparently Travis CI changed recently how they parse HEREDOCs embedded
in the travis configuration file. Strangely, it won't find out EOF
marker anymore. So to work around, we just put the test script into an
actual script and execute it directly instead.
Probably related to this bug report: https://travis-ci.community/t/multiline-commands-have-two-spaces-in-front-breaks-heredocs/2756
=> Remove HEREDOC from travis.yml

configure.ac
since Debian/Ubuntu has renamed that library as arb was already taken
(Backported from master)
=> Search for arb/flint-arb in configure

Makefile.am, renf/refine_embedding.c
This caused trouble for me in a VPATH build.
quoting from https://www.gnu.org/software/autoconf/manual/autoconf-2.61/html_node/Configuration-Headers.html
```
The package should `#include' the configuration header file before any
other header files, to prevent inconsistencies in declarations (for
example, if it redefines const).
To provide for VPATH builds, remember to pass the C compiler a -I.
option (or -I..; whichever directory contains config.h). Even if you use
`#include "config.h"', the preprocessor searches only the directory of
the currently read file, i.e., the source directory, not the build
directory.
With the appropriate -I option, you can use `#include <config.h>'.
Actually, it's a good habit to use it, because in the rare case when the
source directory contains another …
```
=> Follow best practices when including config.h

renf_elem/get_str_pretty.c, renf_elem/test/t-get_str_pretty.c, renfxx/test/t-get_str.cpp, renfxx/test/t-stream.cpp
the fixed size buffer of 20 bytes was not big enough for %f printing.
Instead we now rely on Arb's printing to produce reasonable outputs.
=> Fix printing of large values

.travis.yml, Makefile.am
This is another fix to handle -lflint-arb on Debian, follow up from #82. (Sorry for missing this earlier.)
=> Backport libeantic*_la_LIBADD changes from master 

renf_elem/get_str_pretty.c
the standard does not guarantee the sign of isinf(). That's just what
GNU libc does.
=> Use isinf() in a standard-conforming way

e-antic/renf_elem.h
the exponent was forced to be ulong in
d5554ff32934a323e1ce45932ad7bf2a2244cd59 but this code was not removed.
=> Remove unused code path

e-antic/e-antic.h, e-antic/poly_extra.h, e-antic/renfxx.h, nf_elem/mul.c, nf_elem/reduce.c
With the changes e-antic should accept all Flint versions from 2.5.2 on. The changes have been tested in the Normaliz Travis builds with Flint 2.6.0 (Linux) and 2.6.1 (Mac).
=> Allowing Flint versions >= 2.5.2

.gitignore
this file is read e.g. by clangd which some editors use.
=> gitignore compile_flags.txt

Makefile.am, e-antic/renfxx_cereal.h, renfxx/test/t-cereal.cpp, renfxx/test/t-stream.cpp
also improves testing and removes some fmpq leftovers.
=> Compress cereal output

.travis.yml, Makefile.am, configure.ac, renfxx/benchmark/b-constructor.cpp, renfxx/benchmark/main.cpp, renfxx/renf_class.cpp
fixes #115
The benchmarks do not run in the CI yet (in particular they are not recorded anywhere.) I guess I would eventually like to use the same setup that I use for the flatsurf stack here. But let's see about that in a separate PR.
I added one sample benchmark (which means that flow decomposition will now only use 65% of the time…)
=> Add Benchmarks

.gitignore, NEWS, README.md, news/100.rst, news/TEMPLATE.rst, news/rever.rst, rever.xsh
fixes #123
Once this has been merged, we should be able to release a new version with:
```sh
git fetch origin
git checkout master
git reset --hard origin/master
rever 1.0.0-rc2
```
=> Release with rever

.gitignore, NEWS, README.md, e-antic/renfxx.h, news/100.rst, news/TEMPLATE.rst, news/rever.rst, renfxx/renf_class.cpp, renfxx/renf_elem_class.cpp, rever.xsh
When I added the noexcepts I had a wrong concept on what these are good for. I am now following the advice given in https://akrzemi1.wordpress.com/2011/06/10/using-noexcept. I.e., we only use noexcept where it is actually true (most operations might end up allocating memory so they are not noexcept) and we also only put them when there is a benefit in doing so (mostly move operations so std containers use a faster code path.)
=> Drop noexcept qualifiers

e-antic/renfxx.h, news/vector.rst, renfxx/renf_elem_class.cpp, renfxx/test/t-constructor.cpp
that were accidentally removed in 39e1215e421e128b230fb62ff88ae0ac9b6414e7.
=> implement vector constructors

news/TEMPLATE.rst, news/factory.rst, renfxx/renf_class.cpp, renfxx/test/main.cpp, rever.xsh
We recently simplified the unique-factory that is also used by
exact-real quite a bit. This performs the necessary changes to e-antic
and also speeds up renf_class::operator== which now uses the fact that
renf_class are unique parents so equality can be decided by comparing
poniters.
=> Adapt to simplified unique-factory

renf_elem/fdiv.c
arb_radref is not the diameter but the radius. So to single out a unique
integer, it must be <½. Note that this is again not caught by the tests
because we are not generating enough small numbers.
=> Fix bug in fdiv

doc/news/stdfunction.rst, libeantic/benchmark/Makefile.am, libeantic/benchmark/renfxx/b-arithmetic.cpp, libeantic/srcxx/renf_elem_class.cpp
This saves a few cycles with rather trivial number field elements.
Before:
```
TrivialAddition<renf_elem_class>             63.9 ns         63.9 ns     10316432
TrivialMultiplication<renf_elem_class>       56.8 ns         56.8 ns     13335032
TrivialSubtraction<renf_elem_class>          68.4 ns         68.4 ns     11463610
TrivialDivision<renf_elem_class>              126 ns          126 ns      5095247
```
After:
```
TrivialAddition<renf_elem_class>             56.6 ns         56.6 ns     12140297
TrivialMultiplication<renf_elem_class>       48.2 ns         48.2 ns     14852299
TrivialSubtraction<renf_elem_class>          52.4 ns         52.4 ns     14056737
TrivialDivision<renf_elem_class>              118 ns          118 ns      5972146
```
=> Avoid std::function() overhead in arithmetic

pyeantic/environment.yml, pyeantic/recipe/meta.yaml
since some intermediate versions have problems with some serializations
=> use latest cppyy when testing

.github/workflows/coverage.yml, .github/workflows/doc.yml, .github/workflows/test.yml, doc/manual/Makefile.am, doc/news/python310.rst, doc/news/pythonpath.rst, libeantic/environment.yml, pyeantic/recipe/conda_build_config.yaml, pyeantic/test/bin/python.in
by making sure that disable-pytest comes before site-packages.
---
Checklist
---
Dependencies
=> Fix failing doctests when pytest is installed

doc/news/setup.rst, pyeantic/src/setup.py.in
Importing Setuptools breaks some of distutils so they need to be
imported in the correct order.
Checklist
=> Fix import order in setup.py

.github/workflows/test.yml, doc/news/strict-binop.rst, libeantic/benchmark/renfxx/b-arithmetic.cpp, libeantic/environment.yml, libeantic/srcxx/renf_elem_class.cpp, libeantic/test/byexample/extensions/cxx.py
and print a deprecation warning if they do not match.
Fixes #126.
Checklist
=> Require parents of binary operations to match

.github/workflows/lint.yml, doc/news/cereal-legacy.rst, libeantic/configure.ac, libeantic/e-antic/cereal.hpp, libeantic/test/renfxx/t-cereal.cpp
we have lots of these in the flatsurvey database so it is convenient to
be able to restore them.
Also adapt to cereal >=1.3.1, i.e., fixes https://github.com/flatsurf/e-antic/issues/224
=> Fix deserialization of <1.0.0 cereal objects

doc/news/cereal-no-exception.rst, libeantic/e-antic/cereal.hpp, libeantic/test/renfxx/t-cereal.cpp
=> Fix unpickling of old cereal objects from Python

binder/environment.yml, doc/news/binder.rst
it contains lots of old versions with broken pins. These versions get
randomly pulled in sometimes and cause things to break in quite bizarre
ways.
We release all our packages very frequently, so there is no need to use
nightly releases here.
=> Do not use flatsurf channel

doc/environment.yml, doc/news/pipdeps.rst, pyeantic/environment.yml
since we want (binary) dependencies to always come from conda-forge instead to avoid incompatibilities.
=> Do not silently pull in dependencies from PyPI in CI

.github/workflows/doc.yml, .github/workflows/test.yml, doc/environment.yml, doc/news/unitialized.rst, libeantic/environment.yml, libeantic/src/fmpq_poly_extra/evaluate.c, libeantic/src/fmpz_poly_extra/evaluate.c, pyeantic/environment.yml, pyeantic/src/pyeantic/cppyy_eantic.py
the evaluation code here uses the variable res as a temporary when it is not aliased. Otherwise, it creates a new temporary. This optimization is probably there for a reason but not only the latest GCC finds this confusing and complains about rres being possibly uninitialized. We try to make this easier to read and get rid of the compiler warning.
Checklist
=> Silence compiler warnings about unitialized variables

doc/news/sig2exc.rst, pyeantic/src/pyeantic/cppyy_eantic.py
=> Do not set __sig2exc__ if unspported

libeantic/srcxx/renf_elem_class.cpp
```
CXX      renf_elem_class.lo
renf_elem_class.cpp: In function 'eantic::renf_elem_class& eantic::{anonymous}::binop_mpz(eantic::renf_elem_class&, const mpz_class&)':
renf_elem_class.cpp:157:5: error: there are no arguments to 'fmpz_init_set_readonly' that depend on a template parameter, so a declaration of 'fmpz_init_set_readonly' must be available [-Wtemplate-body]
157 |     fmpz_init_set_readonly(r, rhs.get_mpz_t());
```
fmpq.h and fmpz.h evaluate the gmp-internal macro ``__GMP_H__`` to determine if functions with GMP types should be offered, making inclusion of <gmp.h> before any flint headers mandatory.
=> build: fix build failure with flint 3.2
