Makefile.am, configure.ac, e-antic/poly_extra.h, e-antic/renfxx.h, renfxx/renf_elem_class.cpp
also set the .so number to 1.0.0 (which is not semantic versioning but
now just happens to be the same.)
=> Set .so version number to 1.0.0

renfxx/renf_class.cpp, renfxx/renf_elem_class.cpp, renfxx/test/t-cmp.cpp
but not in identical C++ wrappers
=> Allow comparison of elements that live in equal fields

e-antic/renfxx.h
I do not understand your test suite, that is why I added some tests.
=> Added renf constructor for fmpq poly

e-antic/renfxx.h, renfxx/renf_class.cpp
=> Do not pass renf_t by reference

poly_extra/test/t-fmpz_poly_isolate_real_roots.c
Should fix one of the two problems from #61
=> use 32 bit integers for poly_extra test suite

.gitignore, Makefile.am, e-antic/.gitignore, e-antic/e-antic.h.in
=> Help CLING to find libeantic(xx)

.travis.yml, Makefile.am, configure.ac, renf/refine_embedding.c, renf/test/t-thread.c
=> Make pthread optional

configure.ac
probably that was some copy & paste mistake of mine.
=> Actually detect pthread unless --without-pthread

.travis.yml, renfxx/test/t-stream.cpp
Ubuntu cosmic (18.10) has reaced its end of life. We switch to the current LTS binoic (18.04 LTS).
=> Fix travis script

Makefile.am, e-antic/renfxx.h, e-antic/renfxx_cereal.h, renf/test/rand_generator.hpp, renf/test/renf_generator.hpp, renf_elem/test/renf_elem_generator.hpp, renfxx/renf_class.cpp, renfxx/renf_elem_class.cpp, renfxx/test/renf_class_generator.hpp, renfxx/test/renf_elem_class_generator.hpp, renfxx/test/t-assignment.cpp, renfxx/test/t-cereal.cpp, renfxx/test/t-constructor.cpp, renfxx/test/t-get.cpp, renfxx/test/t-get_num_den.cpp, renfxx/test/t-get_str.cpp, renfxx/test/t-stream.cpp
=> Remove fmpq_t from renf_elem_class

e-antic/renfxx.h, renfxx/test/t-assignment.cpp
=> copy gen_name in assignment of renf_class

README.md
=> Mention that submodule update is necessary for clones

README.md
I guess it should not say C in the title if it is C/C++ (and actually
also Python) by now.
Also the -- looks bad on github so I replaced it with a emdash (I
think.)
=> minor cleanup of README

e-antic/renfxx.h, news/free.rst, renfxx/renf_elem_class.cpp
=> Make comparison operators free

Makefile.am, e-antic/renf_elem.h, news/fdiv.rst, renf_elem/fdiv.c, renf_elem/rounding_template.h, renf_elem/test/t-binop.cpp
=> implement floor division

.travis.yml
That happens when you stop thinking once every test passes. Many of the lines that are not green have/had a bug: https://codecov.io/gh/videlec/e-antic/src/4050f1f485c8d002ff077810ad7b8eddb7c87cfe/renf_elem/fdiv.c
=> enable coverage reporting

.github/workflows/ci-sage.yml
Preview: https://github.com/mkoeppe/e-antic/actions/runs/152354380
=> Add Continuous Integration with Sage

doc/news/no-arbflint.rst, libeantic/e-antic/renfxx.h, libeantic/e-antic/renfxx_cereal.h, libeantic/srcxx/libeanticxx.map, libeantic/srcxx/renf_class.cpp
=> drop cereal dependency on arb/flint symbols

.travis.yml, e-antic/nf_elem.h, nf_elem/get_fmpz_mod_poly.c, nf_elem/test/t-get_fmpz_mod_poly.c, poly_extra/fmpz_poly_randtest_irreducible.c
based on https://github.com/archlinux/svntogit-community/blob/packages/e-antic/trunk/e-antic-flint-2.7.patch
=> Add FLINT 2.7 support, keep FLINT 2.6 support

doc/news/realalg.rst, pyeantic/Makefile.am, pyeantic/test/Makefile.am, pyeantic/test/python-doctest.sh.in, pyeantic/test/realalg-doctest.sh.in, pyeantic/test/sage-doctest.sh.in
=> do not test realalg & sage in regular doctesting

doc/news/parse.rst, pyeantic/src/pyeantic/real_embedded_number_field.py
=> Fix parsing of trivial extension Q[x]/(x-1)

doc/news/err.rst, libeantic/src/renf/refine_embedding.c
=> Remove unused includes

doc/news/fedora.rst, libeantic/configure.ac
=> Hint at non-standard header location for Fedora

doc/news/fedora-warn.rst, libeantic/srcxx/renf_elem_class.cpp
=> Fix warning on Fedora with GCC 11.2.1

.github/workflows/lint.yml, doc/news/cmpsgn.rst, libeantic/e-antic/renf_elem.h, libeantic/src/fmpz_poly_extra/bisection_step_arb.c, libeantic/src/renf_elem/fdiv.c, libeantic/src/renf_elem/get_d.c, libeantic/srcxx/renf_elem_class.cpp, libeantic/test/fmpz_poly_extra/t-isolate_real_roots.c, libeantic/test/renf_elem/t-binop.cpp, libeantic/test/renf_elem/t-cmp.c, libeantic/test/renf_elem/t-cmp_fmpq.c, libeantic/test/renf_elem/t-get_cfrac.c
=> Do not assume that _cmp functions return -1, 0, 1

doc/news/version-dist.rst, libeantic/src/Makefile.am, libeantic/srcxx/Makefile.am
=> Distribute version script files with tarball

pyeantic/src/pyeantic/cppyy_eantic.py
=> Update comment on need for renf_elem_class wrapper

doc/news/isnormal.rst, libeantic/test/renf_elem/t-get_d.cpp
see https://trac.sagemath.org/ticket/31588#comment:18
=> Fix compilation error

doc/news/real_embedded_number_field_cache.rst, pyeantic/environment.yml, pyeantic/src/pyeantic/real_embedded_number_field.py
see https://github.com/flatsurf/flatsurvey/issues/33#issuecomment-1086738166
Checklist
=> Cache embedding normalization

.github/workflows/test.yml
it stopped working since the tmate service was suspended.
=> Disable tmate debugging in CI

doc/manual/libeantic/extra.css, doc/manual/libeantic/mkdocs.yml.in, doc/manual/pyeantic/_static/extra.css, doc/manual/pyeantic/conf.py, doc/news/logo.rst
=> Add logo to documentation

.github/workflows/test.yml, doc/news/catch2139.rst
=> Upgrade catch

doc/news/news.rst, libeantic/test/fmpq_poly_extra/t-evaluate.c, libeantic/test/fmpz_poly_extra/t-has_real_root.c, libeantic/test/fmpz_poly_extra/t-num_real_roots.c, libeantic/test/fmpz_poly_extra/t-num_real_roots_upper_bound.c, libeantic/test/fmpz_poly_extra/t-num_real_roots_vca.c, libeantic/test/fmpz_poly_extra/t-positive_root_upper_bound_2exp.c, libeantic/test/fmpz_poly_extra/t-scale_0_1_fmpq.c, libeantic/test/fmpz_poly_extra/t-squarefree_part.c, libeantic/test/renf/t-init.c, libeantic/test/renf/t-init_nth_root_fmpq.c, libeantic/test/renf/t-randtest.c, libeantic/test/renf/t-real_embeddings.c, libeantic/test/renf_elem/t-ceil.c, libeantic/test/renf_elem/t-cmp.c, libeantic/test/renf_elem/t-cmp_fmpq.c, libeantic/test/renf_elem/t-equal_fmpq.c, libeantic/test/renf_elem/t-floor.c, libeantic/test/renf_elem/t-get_cfrac.c, libeantic/test/renf_elem/t-is_rational.c, libeantic/test/renf_elem/t-pow.c, pyeantic/src/pyeantic/cppyy_eantic.py
=> Add missing news

.github/workflows/test.yml, doc/news/short.rst, libeantic/e-antic/renf_elem_class.hpp, libeantic/srcxx/libeanticxx.map, libeantic/srcxx/renf_elem_class.cpp, libeantic/test/renfxx/t-assignment.cpp, libeantic/test/renfxx/t-binop.cpp, libeantic/test/renfxx/t-cmp.cpp, libeantic/test/renfxx/t-constructor.cpp
=> Add short and unsigned short operators

.github/workflows/test.yml, doc/environment.yml, doc/manual/Makefile.am, doc/manual/robots.txt, doc/news/doc-ball.rst, libeantic/environment.yml, libeantic/recipe/meta.yaml, pyeantic/environment.yml, pyeantic/recipe/meta.yaml, rever.xsh
=> Upload a tarball with the built manual for every release

.codespellrc, .github/workflows/lint.yml, .github/workflows/test.yml, doc/manual/libeantic/overview_cxx.md, doc/news/codespell.rst, libeantic/benchmark/renfxx/renf_elem_class_pool.hpp, libeantic/e-antic/renf.h, libeantic/src/fmpq_poly_extra/set_str_pretty.c, libeantic/src/renf_elem/fdiv.c, libeantic/test/byexample/manual-doctest.sh.in, libeantic/test/fmpq_poly_extra/t-evaluate.c, libeantic/test/renf/t-init.c, pyeantic/src/pyeantic/cppyy_eantic.py, pyeantic/src/pyeantic/real_embedded_number_field.py, pyeantic/src/pyeantic/realalg_conversion.py, pyeantic/test/python-doctest.sh.in
=> Fix typos and run codespell in CI
